/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TourPackagesRouteImport } from './routes/tour-packages'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskPreferencesRouteImport } from './routes/kiosk-preferences'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as FieldGuideRouteImport } from './routes/field-guide'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BusinessDashboardRouteImport } from './routes/business-dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AccommodationsRouteImport } from './routes/accommodations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreAttractionIdRouteImport } from './routes/explore.$attractionId'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesRoute = TourPackagesRouteImport.update({
  id: '/tour-packages',
  path: '/tour-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskPreferencesRoute = KioskPreferencesRouteImport.update({
  id: '/kiosk-preferences',
  path: '/kiosk-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldGuideRoute = FieldGuideRouteImport.update({
  id: '/field-guide',
  path: '/field-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsRoute = AccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAttractionIdRoute = ExploreAttractionIdRouteImport.update({
  id: '/$attractionId',
  path: '/$attractionId',
  getParentRoute: () => ExploreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/attractions': typeof AttractionsRoute
  '/bookings': typeof BookingsRoute
  '/business-dashboard': typeof BusinessDashboardRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/favourites': typeof FavouritesRoute
  '/feedback': typeof FeedbackRoute
  '/field-guide': typeof FieldGuideRoute
  '/itinerary': typeof ItineraryRoute
  '/kiosk-preferences': typeof KioskPreferencesRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/tour-packages': typeof TourPackagesRoute
  '/transport': typeof TransportRoute
  '/explore/$attractionId': typeof ExploreAttractionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/attractions': typeof AttractionsRoute
  '/bookings': typeof BookingsRoute
  '/business-dashboard': typeof BusinessDashboardRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/favourites': typeof FavouritesRoute
  '/feedback': typeof FeedbackRoute
  '/field-guide': typeof FieldGuideRoute
  '/itinerary': typeof ItineraryRoute
  '/kiosk-preferences': typeof KioskPreferencesRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/tour-packages': typeof TourPackagesRoute
  '/transport': typeof TransportRoute
  '/explore/$attractionId': typeof ExploreAttractionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accommodations': typeof AccommodationsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/attractions': typeof AttractionsRoute
  '/bookings': typeof BookingsRoute
  '/business-dashboard': typeof BusinessDashboardRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/favourites': typeof FavouritesRoute
  '/feedback': typeof FeedbackRoute
  '/field-guide': typeof FieldGuideRoute
  '/itinerary': typeof ItineraryRoute
  '/kiosk-preferences': typeof KioskPreferencesRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sos': typeof SosRoute
  '/tour-packages': typeof TourPackagesRoute
  '/transport': typeof TransportRoute
  '/explore/$attractionId': typeof ExploreAttractionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accommodations'
    | '/admin-dashboard'
    | '/attractions'
    | '/bookings'
    | '/business-dashboard'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/favourites'
    | '/feedback'
    | '/field-guide'
    | '/itinerary'
    | '/kiosk-preferences'
    | '/login'
    | '/maps'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/sos'
    | '/tour-packages'
    | '/transport'
    | '/explore/$attractionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accommodations'
    | '/admin-dashboard'
    | '/attractions'
    | '/bookings'
    | '/business-dashboard'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/favourites'
    | '/feedback'
    | '/field-guide'
    | '/itinerary'
    | '/kiosk-preferences'
    | '/login'
    | '/maps'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/sos'
    | '/tour-packages'
    | '/transport'
    | '/explore/$attractionId'
  id:
    | '__root__'
    | '/'
    | '/accommodations'
    | '/admin-dashboard'
    | '/attractions'
    | '/bookings'
    | '/business-dashboard'
    | '/events'
    | '/explore'
    | '/favorites'
    | '/favourites'
    | '/feedback'
    | '/field-guide'
    | '/itinerary'
    | '/kiosk-preferences'
    | '/login'
    | '/maps'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/sos'
    | '/tour-packages'
    | '/transport'
    | '/explore/$attractionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccommodationsRoute: typeof AccommodationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AttractionsRoute: typeof AttractionsRoute
  BookingsRoute: typeof BookingsRoute
  BusinessDashboardRoute: typeof BusinessDashboardRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  FavouritesRoute: typeof FavouritesRoute
  FeedbackRoute: typeof FeedbackRoute
  FieldGuideRoute: typeof FieldGuideRoute
  ItineraryRoute: typeof ItineraryRoute
  KioskPreferencesRoute: typeof KioskPreferencesRoute
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SosRoute: typeof SosRoute
  TourPackagesRoute: typeof TourPackagesRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages': {
      id: '/tour-packages'
      path: '/tour-packages'
      fullPath: '/tour-packages'
      preLoaderRoute: typeof TourPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk-preferences': {
      id: '/kiosk-preferences'
      path: '/kiosk-preferences'
      fullPath: '/kiosk-preferences'
      preLoaderRoute: typeof KioskPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-guide': {
      id: '/field-guide'
      path: '/field-guide'
      fullPath: '/field-guide'
      preLoaderRoute: typeof FieldGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-dashboard': {
      id: '/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/business-dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations': {
      id: '/accommodations'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$attractionId': {
      id: '/explore/$attractionId'
      path: '/$attractionId'
      fullPath: '/explore/$attractionId'
      preLoaderRoute: typeof ExploreAttractionIdRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreAttractionIdRoute: typeof ExploreAttractionIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreAttractionIdRoute: ExploreAttractionIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationsRoute: AccommodationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AttractionsRoute: AttractionsRoute,
  BookingsRoute: BookingsRoute,
  BusinessDashboardRoute: BusinessDashboardRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  FavouritesRoute: FavouritesRoute,
  FeedbackRoute: FeedbackRoute,
  FieldGuideRoute: FieldGuideRoute,
  ItineraryRoute: ItineraryRoute,
  KioskPreferencesRoute: KioskPreferencesRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SosRoute: SosRoute,
  TourPackagesRoute: TourPackagesRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.jsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
