/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TourPackagesRouteImport } from './routes/tour-packages'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskPreferencesRouteImport } from './routes/kiosk-preferences'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as FieldGuideRouteImport } from './routes/field-guide'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BusinessDashboardRouteImport } from './routes/business-dashboard'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AccommodationsRouteImport } from './routes/accommodations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreAttractionIdRouteImport } from './routes/explore.$attractionId'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
})
const TourPackagesRoute = TourPackagesRouteImport.update({
  id: '/tour-packages',
  path: '/tour-packages',
  getParentRoute: () => rootRouteImport,
})
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
})
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
})
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
})
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
})
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const KioskPreferencesRoute = KioskPreferencesRouteImport.update({
  id: '/kiosk-preferences',
  path: '/kiosk-preferences',
  getParentRoute: () => rootRouteImport,
})
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
})
const FieldGuideRoute = FieldGuideRouteImport.update({
  id: '/field-guide',
  path: '/field-guide',
  getParentRoute: () => rootRouteImport,
})
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
})
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
})
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
})
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
})
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
})
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => rootRouteImport,
})
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
})
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
})
const AccommodationsRoute = AccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const ExploreAttractionIdRoute = ExploreAttractionIdRouteImport.update({
  id: '/$attractionId',
  path: '/$attractionId',
  getParentRoute: () => ExploreRoute,
})

const ExploreRouteChildren = {
  ExploreAttractionIdRoute: ExploreAttractionIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AccommodationsRoute: AccommodationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BookingsRoute: BookingsRoute,
  BusinessDashboardRoute: BusinessDashboardRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  FavouritesRoute: FavouritesRoute,
  FeedbackRoute: FeedbackRoute,
  FieldGuideRoute: FieldGuideRoute,
  ItineraryRoute: ItineraryRoute,
  KioskPreferencesRoute: KioskPreferencesRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SosRoute: SosRoute,
  TourPackagesRoute: TourPackagesRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.jsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
